<?php

	function forum_menu(){

        $items['forums'] = array(
		    'title' => 'Forums',
		    'page callback' => array('forum'),
		    #'access arguments' => array('administer list grades'),
		    'access callback' => TRUE,
		    'file' => 'forum.inc',
	    );
	    
	    $items['get_subject'] = array(
		    'title' => '',
		    'page callback' => array('get_subject'),
		    #'access arguments' => array('administer list grades'),
		    'access callback' => TRUE,
	    );
        
        $items['ask-a-question'] = array(
		    'title' => 'Ask A Question',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('ask_a_question_form'),
		    'access arguments' => array('ask a question'),
		    'access callback' => TRUE,
		    'file' => 'question.inc',
	    );

        /*$items['forum'] = array(
		    'title' => 'Question',
		    'page callback' => array('forum'),
		    #'access arguments' => array('ask a question'),
		    'access callback' => TRUE,
		    'file' => 'question.inc',
	    );*/

        $items['forum/questions'] = array(
		    'title' => 'List Of All Questions',
		    'page callback' => array('_forum_question'),
		    #'access arguments' => array('ask a question'),
		    'access callback' => TRUE,
		    'file' => 'question.inc',
	    );

        $items['forum/question-detail'] = array(
		    'title' => 'Question',
		    'page callback' => array('_question'),
		    'access arguments' => array('Ask A Question'),
		    'access callback' => TRUE,
		    'file' => 'question.inc',
	    );
        
        $items['forum/question-reply'] = array(
		    'title' => 'Ask A Question',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('question_reply_form'),
		    'access arguments' => array('Question Reply'),
		    'access callback' => TRUE,
		    'file' => 'question.inc',
	    );

        $items['forum/question/approval'] = array(
            'title' => 'Questions Waiting For Approval',
		    'page callback' => array('question_waiting_for_approval'),
		    'access arguments' => array('Moderator Approval'),
   		    'access callback' => TRUE,
    	    'file' => 'approval.inc',
        );
        $items['admin/list_grades'] = array(
		    'title' => 'List Grades',
		    'page callback' => array('_list_grades'),
		    'access arguments' => array('administer list grades'),
		    'access callback' => TRUE,
		    'file' => 'grade.inc',
	    );

        $items['admin/list_subjects'] = array(
		    'title' => 'List Subjects',
		    'page callback' => array('_list_subjects'),
		    'access arguments' => array('administer list subjects'),
		    'access callback' => TRUE,
		    'file' => 'subjects.inc',
	    );

	    $items['list/grade/modify'] = array(
		    'title' => 'Modify',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('grade_modify_form'),
		    'access arguments' => array('Modify Grade for Forum'),
		    'access callback' => TRUE,
		    'file' => 'grade.inc',
	    );
	    
	    $items['list/grade/delete'] = array(
		    'title' => 'Delete',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('grade_delete_confirm'),
		    'access arguments' => array('Delete Grade from forum'),
		    'access callback' => TRUE,
		    'file' => 'grade.inc',
	    );
	    $items['list/subject/modify'] = array(
		    'title' => 'Modify',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('subject_modify_form'),
		    'access arguments' => array('Modify Subject for Fourm'),
		    'access callback' => TRUE,
		    'file' => 'subjects.inc',
	    );
	    $items['list/subject/delete'] = array(
		    'title' => 'Delete',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('subject_delete_confirm'),
		    'access arguments' => array('Delete Subject from Forum'),
		    'access callback' => TRUE,
		    'file' => 'subjects.inc',
	    );
	    $items['forum/assign/teacher'] = array(
		    'title' => 'Assign A Teacher',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('assign_teacher_form'),
		    'access arguments' => array('Assign A Teacher'),
		    'access callback' => TRUE,
		    'file' => 'teacher.inc',
	    );
	    $items['admin/settings/extension'] = array(
		    'title' => 'File Extension',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('extensions_allowed_form'),
		    'access arguments' => array('Extensions allowed to upload Attachment'),
		    'access callback' => TRUE,
	    );
	return $items;
	
	}
    
    function extensions_allowed_form($form_state)
    {
        $form['ext_allowed'] = array(
            '#type' => 'textfield',
            '#title' => t('Specify file extensions allowed to upload as a attachment on FORUM.'),
            '#description' => t('Provide file extensions with comma. For example: png, jpg, jpeg'),
            '#size' => 100,
            '#maxlength' => 255,
            '#required' => TRUE,
            '#default_value' => variable_get('exten_allowed', ''),
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Submit')
        );
        return $form;
    }
    
    function extensions_allowed_form_submit($form, &$form_state)
    {
        variable_set('exten_allowed', $form_state['values']['ext_allowed']);
        drupal_set_message(t('Settings updated'), 'status');
    }
    function get_subject()
    {
        $existing_subject_name = '';
        if(isset($_POST['grade']))
        {
            $result_query = db_query('SELECT subject_name,id,grade_id FROM forum_subjects WHERE grade_id = '.$_POST['grade'].' GROUP BY subject_name');
            $existing_subject_name = array();
            while($rows = $result_query->fetchObject()){
                $existing_subject_name[] = $rows;
            }
        }
        echo json_encode($existing_subject_name);
        exit;   
    }    
        
    	
	function forum_permission(){
	    return array(
	        'administer list grades'=> array(
                'title' => t('Administer Open Web Analytics')
            ),
            'Modify Grade for Forum'=> array(
                'title' => t('Modify Grade for Forum')
            ),
            'Delete Grade from forum'=> array(
                'title' => t('Delete Grade from forum')
            ),
            'Modify Subject for Fourm'=> array(
                'title' => t('Modify Subject for Fourm')
            ),
            'Delete Subject from Forum'=> array(
                'title' => t('Delete Subject from Forum')
            ),
            'Ask A Question'=> array(
                'title' => t('Asking A Question on Forum')
            ),
            'Moderator Approval'=> array(
                'title' => t('Questions Waiting For Moderator Approval')
            ),
            'Question Reply'=> array(
                'title' => t('Reply To The Questions')
            ),
        );
	}
	
	function forum_mail($key, &$message, $params)
	{
	    switch ($key) {
            case 'askaquestion':
              // Set headers etc
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];              
                break;
            case 'replyaquestion':
              // Set headers etc
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];              
                break;
            }
            
	}
	
	function forum_init(){
  	  drupal_add_css(drupal_get_path('module', 'forum') .'/question.css');
	}
	
	function forum_form_alter(&$form,$form_state,$form_id)
	{
	    $user = arg(1);
        $user_query = db_query("SELECT * FROM users_extend WHERE uid = '".$user."'");
        
        while($query = $user_query->fetchObject()){
        
          if ($form_id === 'user_profile_form' ) 
          { 
                #$form['account']['mail']['#disabled'] = true;
                $result_grade = db_query('SELECT id,grade_name FROM forum_grades') ->fetchAll();
                $grd_nm = $result_grade[0]->grade_name;
                $grd_id = $result_grade[0]->id;
                $option[''] = '----Select----';        
                foreach ($result_grade as $node) {
                    $option[$node->id] = $node->grade_name;
                }
                $form['fname'] = array(
			        '#type' => 'textfield',
			        '#size' => 30,
			        '#title' => t('First Name'),
			        '#required' => TRUE,
			        '#value' => $query->fname,
			        '#description' => "Please enter your First Name.",
		        );
		        $form['lname'] = array(
			        '#type' => 'textfield',
			        '#size' => 30,
			        '#title' => t('Last Name'),
			        '#required' => TRUE,
			        '#value' => $query->lname,
			        '#description' => "Please enter your Last Name.",
		        );
		        $form['mobile'] = array(
			        '#type' => 'textfield',
			        '#size' => 12,
			        '#title' => t('Mobile No.'),
			        '#required' => TRUE,
			        '#value' => $query->mobile,
			        '#description' => "Please enter your Mobile No.",
			        '#attributes' => array('class' => array('mobile')),
			        '#prefix' => '<div id="errmsg"></div>',
			        
		        );
                $form['grade'] = array(
                    '#title' => t('Grade'),
                    '#type' => 'select',
                    '#options' => $option,
                    '#attributes' => array('class' => array('grade')),
                    '#validated' => TRUE,
                );
                $form['subject'] = array(
                    '#title' => t('Subject'),
                    '#type' => 'select',
                    '#multiple' => TRUE,
                    '#options' => array(''=> '-- Select --'),
                    '#attributes' => array('class' => array('subject')),
                    '#validated' => TRUE
                );
            }
                $form['#submit'][] = 'forum_form_alter_submit';
                return $form;                
          }
    }
    function forum_form_alter_submit(&$form,$form_state)
    {
        $selected_subjects = implode(",",$form_state['values']['subject']);
        //print_r($selected_subjects);
        //die;
        $user = arg(1);
        
        //if ($form_id === 'user_profile_form' ) 
        //{
                $query = "INSERT INTO `users_extend` (`uid`, `fname`, `lname`, `mobile`, `grade`, `subject`) VALUES ('".$user."', '".$form_state['values']['fname']."', '".$form_state['values']['lname']."','".$form_state['values']['mobile']."', '".$form_state['values']['grade']."', '".$selected_subjects."')";
                if(db_query($query))
                {
                    drupal_set_message('Stored successfully');
                }
                else
                {
                    drupal_set_message("Error");
                }
        //}
    }
?>
