<?php

	function forum_menu(){
	
        $items['forums'] = array(
		    'title' => 'Forums',
		    'page callback' => array('forum'),
		    'access callback' => TRUE,
		    'file' => 'forum.inc',
	    );
	    
	    $items['get_subject'] = array(
		    'title' => '',
		    'page callback' => array('get_subject'),
		    'access callback' => TRUE,
	    );
        
        $items['ask-a-question'] = array(
		    'title' => 'Ask A Question',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('ask_a_question_form'),
		    'access arguments' => array('Ask A Question'),
		    'file' => 'question.inc',
	    );

        $items['forum_main'] = array(
		    'title' => 'Question',
		    'page callback' => 'drupal_get_form',
    	    'page arguments' => array('forum_form'),
	    );

        $items['forum/questions'] = array(
		    'title' => 'Questions',
		    'page callback' => array('_forum_question'),
		    'access callback' => TRUE,
		    'file' => 'question.inc',
	    );

        $items['forum/question-detail'] = array(
		    'title' => 'Question Detail',
		    'page callback' => array('_question'),
		    'access arguments' => array('Question Details'),
		    'file' => 'question.inc',
	    );
        $items['forum/question-det-approval'] = array(
            'title' => 'Question In Detail Waiting For Approval',
		    'page callback' => array('question_det_approval'),
		    'access arguments' => array('Question Moderator Approval'),
    	    'file' => 'question-detail-approval.inc',
        );
	    $items['forum/comment-detail'] = array(
		    'title' => 'Question Detail',
		    'page callback' => array('_comment'),
		    'access arguments' => array('Comment Details'),
		    'file' => 'comment.inc',
	    );
        $items['forum/question-reply'] = array(
		    'title' => 'Reply A Question',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('question_reply_form'),
		    'access arguments' => array('Question Reply'),
		    'file' => 'question.inc',
	    );
        $items['forum/search'] = array(
		    'title' => 'Search',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('forum_search'),
		    'access callback' => TRUE,
		    'file' => 'forum.inc',
	    );
	    $items['forum/search/result'] = array(
		    'title' => 'Search Results',
		    'page callback' => 'forum_search_result',
		    'access callback' => TRUE,
		    'file' => 'forum.inc',
	    );
        $items['forum/question/approval'] = array(
            'title' => 'Questions Waiting For Approval',
		    'page callback' => array('question_waiting_for_approval'),
		    'access arguments' => array('Question Moderator Approval'),
    	    'file' => 'approval.inc',
        );
        $items['forum/comment/approval'] = array(
            'title' => 'Comment Waiting For Approval',
		    'page callback' => array('comment_waiting_for_approval'),
		    'access arguments' => array('Comment Moderator Approval'),
    	    'file' => 'comment_approval.inc',
        );
        $items['admin/list_grades'] = array(
		    'title' => 'List Grades',
		    'page callback' => array('_list_grades'),
		    'access arguments' => array('administer list grades'),
		    'file' => 'grade.inc',
	    );
        $items['admin/list_subjects'] = array(
		    'title' => 'List Topics',
		    'page callback' => array('_list_subjects'),
		    'access arguments' => array('administer list subjects'),
		    'file' => 'subjects.inc',
	    );
	    $items['list/grade/modify'] = array(
		    'title' => 'Modify Grades',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('grade_modify_form'),
		    'access arguments' => array('Modify Grade for Forum'),
		    'file' => 'grade.inc',
	    );
	    $items['list/grade/delete'] = array(
		    'title' => 'Delete Grades',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('grade_delete_confirm'),
		    'access arguments' => array('Delete Grade from forum'),
		    'file' => 'grade.inc',
	    );
	    $items['list/subject/modify'] = array(
		    'title' => 'Modify Topics',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('subject_modify_form'),
		    'access arguments' => array('Modify Subject for Fourm'),
		    'file' => 'subjects.inc',
	    );
	    $items['list/subject/delete'] = array(
		    'title' => 'Delete Topics',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('subject_delete_confirm'),
		    'access arguments' => array('Delete Subject from Forum'),
		    'file' => 'subjects.inc',
	    );
	    $items['forum/assign/teacher'] = array(
		    'title' => 'Assign A Teacher',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('assign_teacher_form'),
		    'access arguments' => array('Assign A Teacher'),
		    'file' => 'teacher.inc',
	    );
	    $items['admin/settings/extension'] = array(
		    'title' => 'File Extension',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('extensions_allowed_form'),
		    'access arguments' => array('Extensions allowed to upload Attachment'),
	    );
	    $items['forum/question/search'] = array(
		    'title' => 'Search',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('forum_question_search'),
		    'access callback' => TRUE,
		    'file' => 'approval.inc',
	    );
	    $items['forum/question/search/result'] = array(
		    'title' => 'Question Search Results',
		    'page callback' => 'forum_question_search_result',
		    'access callback' => TRUE,
		    'file' => 'approval.inc',
	    );
	    $items['forum/comment/search'] = array(
		    'title' => 'Search',
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('forum_comment_search'),
		    'access callback' => TRUE,
		    'file' => 'comment_approval.inc',
	    );
	    $items['forum/comment/search/result'] = array(
		    'title' => 'Comment Search Results',
		    'page callback' => 'forum_comment_search_result',
		    'access callback' => TRUE,
		    'file' => 'comment_approval.inc',
	    );
	return $items;
	}
    function forum_form()
    {
    }
    function extensions_allowed_form($form_state)
    {
        $form['ext_allowed'] = array(
            '#type' => 'textfield',
            '#title' => t('Specify file extensions allowed to upload as a attachment on FORUM.'),
            '#description' => t('Provide file extensions with comma. For example: png, jpg, jpeg, docx, pdf, ods'),
            '#size' => 100,
            '#maxlength' => 255,
            '#required' => TRUE,
            '#default_value' => variable_get('exten_allowed', ''),
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Submit')
        );
        return $form;
    }
    function extensions_allowed_form_submit($form, &$form_state)
    {
        variable_set('exten_allowed', $form_state['values']['ext_allowed']);		
        drupal_set_message(t('Settings updated'), 'status');
    }
    function get_subject()
    {
        $existing_subject_name = '';
        if(isset($_POST['grade']))
        {
            $result_query = db_query('SELECT subject_name,id,grade_id FROM forum_subjects WHERE grade_id = '.$_POST['grade'].' GROUP BY subject_name');
            $existing_subject_name = array();
            while($rows = $result_query->fetchObject()){
                $existing_subject_name[] = $rows;
            }
        }
        echo json_encode($existing_subject_name);
        exit;   
    }    
	function forum_permission(){
	    return array(
	        'administer list grades'=> array(
                'title' => t('Administer Open Web Analytics')
            ),
            'Modify Grade for Forum'=> array(
                'title' => t('Modify Grade for Forum')
            ),
            'Delete Grade from forum'=> array(
                'title' => t('Delete Grade from forum')
            ),
            'Modify Subject for Fourm'=> array(
                'title' => t('Modify Subject for Fourm')
            ),
            'Delete Subject from Forum'=> array(
                'title' => t('Delete Subject from Forum')
            ),
            'Ask A Question'=> array(
                'title' => t('Asking A Question on Forum')
            ),
            'Question Moderator Approval'=> array(
                'title' => t('Questions Waiting For Moderator Approval')
            ),
            'Question Reply'=> array(
                'title' => t('Reply To The Questions')
            ),
            'Question Details'=>array(
                'title' => t('Question Details')
            ),
            'Comment Moderator Approval'=>array(
                'title' => t('Comment Moderator Approval')
            ),
			'Comment Details'=>array(
                'title' => t('Comment Details')
            ),
        );
	}
	function forum_mail_alter(&$message) {
        $headers = array(
            'MIME-Version' => '1.0',
            'Content-Type' => 'text/html; charset=iso-8859-1; format=flowed',
            'Content-Transfer-Encoding' => '8Bit',
            'X-Mailer' => 'Drupal',
        );
        foreach ($headers as $key => $value) {
            $message['headers'][$key] = $value;
        }
    }

	function forum_mail($key, &$message, $params)
	{
	    
	    switch ($key) {
            case 'askaquestion':
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];              
                break;
            case 'replyaquestion':
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];              
                break;
            case 'rejectaquestion':
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];
                break;
            case 'replytoquestion':
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];
                break;
			case 'postedquestion':
                $message['subject'] = $params['subject'];
                $message['body'] = $params['body'];
                break;
            }            
	}
	
	function forum_init(){
  	  drupal_add_js(array(
          'forum-style' => array(
          'modalSize' => array('type' => 'fixed','width' => 850,'height' => 550,),
          'animation' => 'fadeIn',
          ),
      ), 'setting');
      drupal_add_css(drupal_get_path('module', 'forum') .'/question.css');
	}
	
	function forum_form_alter(&$form,$form_state,$form_id)
	{
	    $user_arg = arg(1);
	    global $user;
	    $subject_t = array();
		$subject_temp= array();
        $user_query = db_query("SELECT * FROM users_extend WHERE uid = '".$user_arg."'");
		
        if($user_query->rowCount() >0)
        {
            $query = $user_query->fetchObject();
			
			//--- Start - code added by Manjiri
			$res_sql=db_query("select id,subject_name from forum_subjects where grade_id='".$query->grade."'");	
			foreach($res_sql as $temp_sql)
			{
				$subject_temp[$temp_sql->id]=$temp_sql->subject_name;				
			}
			//--- End - code added by Manjiri
            $fname = $query->fname;
            $lname = $query->lname;
            $mobile = $query->mobile;
            $grade = $query->grade;
			$subject = explode(',',$query->subject);
			/*foreach($subject as $temp_sub)
			{
				$subject_t[$temp_sub] = subject($temp_sub);
			}	*/		
        }
        else
        {
            $fname = '';
            $lname = '';
            $mobile = '';
			$grade = '';
			$subject = '';
        }
		
		
          if (($form_id === 'user_profile_form' )||($form_id === 'user_register_form'))
          { 
				$form['account']['name']['#description']='Spaces are allowed, punctuation is not allowed except for periods, hyphens, apostrophes, and underscores.';
                $result_grade = db_query('SELECT id,grade_name FROM forum_grades') ->fetchAll();
                $grd_nm = $result_grade[0]->grade_name;
                $grd_id = $result_grade[0]->id;
				
                $option['0'] = '----Select----';        
                foreach ($result_grade as $node) {
                    $option[$node->id] = $node->grade_name;
                }
                $form['account']['name']['#required'] = FALSE;
                $form['account']['mail']['#required'] = FALSE;
                $form['tfname'] = array(
			        '#type' => 'textfield',
			        '#size' => 30,
			        '#title' => t('First Name'),
			        '#default_value' => $fname,
			        '#description' => "Please enter your First Name.",
		        );
		        $form['tlname'] = array(
			        '#type' => 'textfield',
			        '#size' => 30,
			        '#title' => t('Last Name'),
			        '#default_value' => $lname,
			        '#description' => "Please enter your Last Name.",
		        );
		        $form['tmobile'] = array(
			        '#type' => 'textfield',
			        '#size' => 12,
			        '#title' => t('Mobile No.'),
			        '#default_value' => $mobile,
			        '#description' => "Please enter your Mobile No.",
			        '#attributes' => array('class' => array('mobile')),
			        '#prefix' => '<div id="errmsg"></div>',
			        
		        );
		        
                $form['grade'] = array(
                    '#title' => t('Grade'),
                    '#type' => 'select',
                    '#options' => $option,
					'#default_value' => $grade,
                    '#attributes' => array('class' => array('grade')),
                    '#validated' => TRUE,
                );
                if(($user->uid)&&(!in_array('authentcated user', $user->roles)))
		        {
                   	$form['subject'] = array(
							'#title' => t('Topic'),
							'#type' => 'select',
							'#multiple' => TRUE,													
							'#options' => $subject_temp,	
							'#default_value' => $subject,										
							'#attributes' => array('class' => array('subject'),'selected'=>'selected'),
							'#validated' => TRUE
						);
                }
                array_unshift($form['#validate'], 'forum_form_validate');
                }
				
                $form['#submit'][] = 'forum_form_alter_submit';
                return $form;                
    }
    function forum_form_validate($form,&$form_state)
    {
if(($form_state['values']['name']=='')&&($form_state['values']['mail']=='')&&($form_state['values']['tfname']=='')&&($form_state['values']['tlname']=='')&&($form_state['values']['tmobile']=='')&&($form_state['values']['grade']=='0'))
			{
				form_set_error('name','Please fill in the following details');
				form_set_error('mail');
				form_set_error('tfname');
				form_set_error('tlname');
				form_set_error('tmobile');
				form_set_error('grade');
			}
			if($form_state['values']['name']=='')
			{
			    form_set_error('name', t('Please enter Name'));
			}
			if($form_state['values']['tfname']=='')
			{
			    form_set_error('tfname', t('You must enter First name'));
			}
			if($form_state['values']['tlname']=='')
			{
			    form_set_error('tlname', t('Please enter Last Name'));
			}
            if((strlen(trim($form_state['values']['tmobile'])) !=10)||!is_numeric(trim($form_state['values']['tmobile'])))
            {
                form_set_error('tmobile', t('Please enter 10 mobile number'));
            }
            if($form_state['values']['grade']=='0')
            {
                form_set_error('grade', t('Grade is required!'));
            }
            if($form_state['build_info']['form_id'] == 'user_profile_form')
            {
                if(!$form_state['values']['subject'])
                {
                    form_set_error('subject', t('Please select a proper topic.'));
                }
            }
    }
    function forum_form_alter_submit($form_state,$form_id)
    {
        if (($form_id['build_info']['form_id'] == 'user_profile_form' )||($form_id['build_info']['form_id'] == 'user_register_form')) 
        {
        $fname = $form_state['tfname']['#value'];
        $lname = $form_state['tlname']['#value'];
        $mobile = $form_state['tmobile']['#value'];
        if($form_state['subject']['#value'] == '-Select-')
        {
            $form_state['subject']['#value'] = '0';
            //$form_state['subject']['#value'] = $form_state['subject']['#value'];
		}
		else
		{
		    $selected_subjects = implode(",",$form_state['subject']['#value']);
		}
		    
        if($form_state['subject']['#value'])
        {
            if($form_id['build_info']['form_id'] == 'user_register_form')
            { 
                $add_u = db_query("SELECT max(uid) as usr FROM users")->fetchAll();
                $user_add = $add_u[0]->usr;
            }
            else 
            {
                $user_add = arg(1);
            }
            
		    {
		        $form_state['subject']['#value']['-Select-'] = '0';
		        $form_state['subject']['#value'] = $form_state['subject']['#value']['-Select-'];
		        var_dump($form_state['subject']['#value']);
		    }
            $user_db_exist = db_query('SELECT count(*) as cnt FROM users_extend WHERE uid='.$user_add)->fetchAll();
            if($user_db_exist[0]->cnt > 0)
            {
                $query = "UPDATE `users_extend` SET `fname`='".$fname."',`lname`='".$lname."',`mobile`='".$mobile."',`grade`='".$form_state['grade']['#value']."',`subject`='".$selected_subjects."' WHERE uid = '".$user_add."'";
            }
            else
            {
                $query = "INSERT INTO `users_extend` (`uid`, `fname`, `lname`, `mobile`, `grade`, `subject`) VALUES ('".$user_add."', '".$fname."', '".$lname."','".$mobile."', '".$form_state['grade']['#value']."', '".$selected_subjects."')";
            }    
            if(db_query($query))
            {
                drupal_set_message('Stored successfully');
            }
            else
            {
                drupal_set_message("Error");
            }
        }
        else
        {
            if($form_id['build_info']['form_id'] == 'user_register_form')
            { 
                $add_u = db_query("SELECT max(uid) as usr FROM users")->fetchAll();
                $user_add = $add_u[0]->usr;
            }
            else 
            {
                $user_add = arg(1);
            }
            if($form_state['subject']['#value']['-Select-'] == '-Select-')
		    {
		        $form_state['subject']['#value']['-Select-'] = '0';
		    }
            $grade = $form_state['grade']['#value'];
            $user_db_exist = db_query('SELECT count(*) as cnt FROM users_extend WHERE uid='.$user_add)->fetchAll();
            
            if($user_db_exist[0]->cnt > 0)
            {
                $query = "UPDATE `users_extend` SET `fname`='".$fname."',`lname`='".$lname."',`mobile`='".$mobile."',`grade`='".$grade."',`subject`='0' WHERE uid = '".$user_add."'";
            }
            else
            {
                $query = "INSERT INTO `users_extend` (`uid`, `fname`, `lname`, `mobile`, `grade`, `subject`) VALUES ('".$user_add."', '".$fname."', '".$lname."','".$mobile."', '".$grade."', '0')";
            }    
            if(db_query($query))
            {
                drupal_set_message('Stored successfully');
            }
            else
            {
                drupal_set_message("Error");
            }
        }
        }
    }
    function ago($timestamp){
        $difference = time() - strtotime($timestamp);
        $text = format_interval($difference, 1) . " ago";
        return $text;    
    }
    
    function grade($grade)
    {
	
        $grade_query = db_query('SELECT grade_name FROM forum_grades WHERE id ='.$grade)->fetchAll();
	  	if($grade_query)
        {
            return $grade_query[0]->grade_name;
        }
        else
        {
            return 0;
        }
    }
    
    function subject($subject)
    {
        if($subject)
        {
			$subject_query1 = db_query('SELECT subject_name FROM forum_subjects WHERE id ='.$subject)->fetchObject();
            return $subject_query1->subject_name;
        }
        else
        {
            return '';
        }
    }
    function truncate_chars($text, $limit, $ellipsis = '...')
    {
        if( strlen($text) > $limit )
        {
            $text = trim(substr($text, 0, $limit)) . $ellipsis; 
        }
    return $text;
    }
    function role_mail($role, $grade, $subject)
    {
        $rid = array_search($role, user_roles());
        $temp = array();
        if($role == 'admin moderator')
        {
            $mail_id = db_query("SELECT DISTINCT u.mail FROM users_roles as ur, users u WHERE ur.rid = '".$rid."' AND ur.uid = u.uid");
        }
        else if($role == 'moderator')
        {
            $mail_id = db_query("SELECT u.mail FROM users_roles as ur, users u, users_extend ue WHERE ur.rid = '".$rid."' AND ur.uid = u.uid AND ur.uid = ue.uid AND ue.grade = '".$grade."' AND FIND_IN_SET('".$subject."',ue.subject) > 0");
        }
        else if($role == 'teacher')
        {
            $mail_id = db_query("SELECT u.mail FROM users_roles as ur, users u, users_extend ue WHERE ur.rid = '".$rid."' AND ur.uid = u.uid AND ur.uid = ue.uid AND ue.grade = '".$grade."' AND FIND_IN_SET('".$subject."',ue.subject) > 0");
        }
        while($role_mail = $mail_id->fetchObject())
        {
            $temp[] = $role_mail->mail;
        }
        if (count($temp) === 1) 
        {
            $grp_mail = $temp[0];
        }
        else
        {
            $grp_mail = implode(",",$temp);
        }
        return $grp_mail;
    }
    function student_mail($q_id)
    {
        $stu_mail_id = db_query("SELECT mail FROM forum_questions fq, users u WHERE fq.id = '".$q_id."' AND fq.user_id = u.uid")->fetchObject();
        return $stu_mail_id->mail;
    }
	 /*---- Code to be embedded Waiting approval------*/
    function comment_status($comment_status)
    {
        if($comment_status=='0')
        {
            return "Waiting For Approval";
        }
        else if($comment_status=='1')
        {
            return "Approved";
        }
        else if($comment_status=='-1')
        {
            return "Rejected";
        }
    }
    /*---------------------------------------------*/
?>
